resolver: lts-4.0
image:
  containers:
    - base: "fpco/ubuntu-with-libgmp:14.04"
      entrypoints:
        - stack
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
extra-deps:
# Should be removed once gitrev is updated in stackage (lts-5)
- gitrev-1.2.0
