resolver: lts-5.3
image:
  containers:
    - base: "fpco/ubuntu-with-libgmp:14.04"
      entrypoints:
        - stack
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
extra-deps:
- path-io-0.3.1
- hpack-0.9.0
